-- BoilerWatch / BK3 Platform
-- Multi-company tenancy foundation
-- Originally applied through the Supabase SQL Editor.

create table if not exists public.tenants (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  name text not null,
  slug text not null unique,

  tenant_type text not null default 'Contractor',
  logo_url text,
  primary_color text,
  secondary_color text,

  is_active boolean not null default true,
  white_label_enabled boolean not null default false,

  notes text
);

alter table public.tenants enable row level security;

insert into public.tenants (
  name,
  slug,
  tenant_type,
  white_label_enabled
)
select
  'SF Boiler Permits',
  'sf-boiler-permits',
  'Contractor',
  true
where not exists (
  select 1
  from public.tenants
  where slug = 'sf-boiler-permits'
);

alter table public.customers
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.organizations
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.properties
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.equipment
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.permits
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.service_requests
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.notes
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.devices
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.sensors
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.telemetry
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

alter table public.leads
  add column if not exists tenant_id bigint
  references public.tenants(id)
  on delete cascade;

do $$
declare
  v_tenant_id bigint;
begin
  select id
  into v_tenant_id
  from public.tenants
  where slug = 'sf-boiler-permits';

  if v_tenant_id is null then
    raise exception 'SF Boiler Permits tenant was not found';
  end if;

  update public.customers
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.organizations
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.properties
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.equipment
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.permits
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.service_requests
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.notes
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.devices
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.sensors
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.telemetry
  set tenant_id = v_tenant_id
  where tenant_id is null;

  update public.leads
  set tenant_id = v_tenant_id
  where tenant_id is null;
end;
$$;

create index if not exists customers_tenant_id_idx
  on public.customers(tenant_id);

create index if not exists properties_tenant_id_idx
  on public.properties(tenant_id);

create index if not exists equipment_tenant_id_idx
  on public.equipment(tenant_id);

create index if not exists service_requests_tenant_id_idx
  on public.service_requests(tenant_id);

create index if not exists devices_tenant_id_idx
  on public.devices(tenant_id);

create index if not exists sensors_tenant_id_idx
  on public.sensors(tenant_id);

create index if not exists telemetry_tenant_id_idx
  on public.telemetry(tenant_id);

create index if not exists leads_tenant_id_idx
  on public.leads(tenant_id);